### ISSUE TITLE
Deleting a message messes up subsequent messages

### ISSUE THREAD

**Issue by t0xicCode** [mailhog/MailHog-UI#10]
Test case:

* Have MailHog UI running with a few messages (we had ~20).
* Delete a message halfway in the list.
* Open a message that was after the deleted message.

Expected result: The message opens up.
Actual result: A different message opens up (the one above it seems).

**Comment by ian-kent** [comment]
thanks @t0xicCode, i'll investigate!

**Comment by ian-kent** [comment]
hopefully fixed, but reopen if that didn't work :smile:
