### ISSUE TITLE
Case insensitive Content-Type not handled as html

### ISSUE THREAD

**Issue by fliespl** [mailhog/MailHog-UI#20]
If mailer uses `content-type`, `Content-type` instead of `Content-Type` message will not be displayed as html since case sensitive key match is being used in controller.js.

**Comment by ian-kent** [comment]
I think this is the same as mailhog/MailHog#113, and should be fixed by c2d0e00c01de4212a84a8d183182ffa8941252fa

Let me know if it's still broken after the next release

**Comment by 123andy** [comment]
Hi @ian-kent - The case sensitivity of the header keys is still an issue.  It appears the code uses Content-Type explicitly in numerous places:

Perhaps instead of the patch above, a fix that modifies the `message.Content.Headers['keys']` to be of the proper format on parse would be easier:

```javascript
for(var header in message.Content.Headers) {
	if(header.toLowerCase() == 'content-type' && header != 'Content-Type') {
		message.Content.Headers['Content-Type'] = message.Content.Headers[header];
		delete message.Content.Headers[header];
		break;
	}
}
```

Or, perhaps just make all titlecase:

```javascript
for(var header in message.Content.Headers) {
  var parts = header.split("-");
  for (var part in parts) {
    var s = parts[part];
    parts[part] = s.charAt(0).toUpperCase() + s.substr(1).toLowerCase();
  }
  var newHeader = parts.join("-");
  if(header =! newHeader) {
    message.Content.Headers[newHeader] = message.Content.Headers[header];
    delete message.Content.Headers[header];
  }
}
```

**Comment by webprogrammierer** [comment]
The problem still exist. Why can't this be solved?

**Comment by dimitropoulos** [comment]
@ian-kent since you asked, just wanted to let you know that it's still an issue

**Comment by webprogrammierer** [comment]
For years
